## Append samples of your project ##
resources:
- qdrant_v1alpha1_qdrantcluster.yaml
- qdrant_v1alpha1_qdrantcollection.yaml
- qdrant_v1alpha1_qdrantbackup.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
